# Generated by Django 3.2 on 2021-06-08 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20210508_2249'),
        ('users', '0003_auto_20210414_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='viewed_posts',
            field=models.ManyToManyField(to='posts.Post'),
        ),
    ]
