# Generated by Django 3.2 on 2021-06-08 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20210508_2249'),
        ('users', '0004_userprofile_viewed_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='viewed_posts',
            field=models.ManyToManyField(related_name='views', to='posts.Post'),
        ),
    ]
